base: 
  # Dataset Config
  dataset: "cataract101"
  num_class: 10
  data_dir: "./cataract-101/data/"
  label_dir: "./cataract-101/label/"

  # Device Config
  gpus: [0,1,2]
  num_workers: 32
  batch_size: 48

  # Train / Query / Database Split Config
  train_index: [1, 2, 4, 6, 7, 8, 9, 10, 12, 14, 15, 16, 18, 19, 21, 22, 23, 24, 28, 29, 31, 32, 34, 35, 36, 37, 38, 39, 40, 42, 46, 48, 53, 55, 57, 59, 62, 63, 64, 66, 68, 70, 71, 72, 73, 74, 75, 79, 82, 83, 85, 86, 87, 89, 90, 92, 94, 95, 96, 97, 98]
  query_index: [5, 93, 84, 51, 44, 56, 0, 67, 30, 78]
  database_index: [3, 11, 13, 17, 20, 25, 26, 27, 33, 41, 43, 45, 47, 49, 50, 52, 54, 58, 60, 61, 65, 69, 76, 77, 80, 81, 88, 91, 99, 100]

  # Model Config
  code_length: 256
  n_frame: 20
  duration: 20
train: 
  epochs: 150
  warmup_epochs: 5
  lr: 1.0e-4
  min_lr: 1.0e-6
  weight_decay: 1.0e-5
  optim: adamw
  scheduler_gamma: 0.98
  print_freq: 5
  save_freq: 5
  checkpoint: ~
test:
  model_path: "./data/model/cataract101_150.pth"